development:
  sessions:
    default:
      database: smartstock_development
      hosts:
        - 127.0.0.1:27017
      identity_map_enabled: true

test:
  sessions:
    default:
      database: smartstock_test
      hosts:
        - 127.0.0.1:27017
      identity_map_enabled: true

staging:
  sessions:
    default:
      database: smartstock
      hosts:
        - 127.0.0.1:27017
      identity_map_enabled: true

production:
  sessions:
    default:
      database: smartstock
      hosts:
        - 127.0.0.1:27017
      identity_map_enabled: true
